version: '3'

services:
  postgres:
    container_name: 'app-name-postgres'
    restart: unless-stopped
    image: 'postgres:13@sha256:94bbd9a92e24c309af48c695c4d253844b5839148f92428941d55b15629ca3f5'
    ports:
      - '15432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: postgres
  nextjs:
    build: ./
    ports:
      - 3000:3000

volumes:
  pgdata: {}
